<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class DeclarantPersonalInfo extends Model
{
    protected $fillable = [
        'declarant_registration_id',
        'full_name',
        'name_with_initials',
        'name_with_initials_eng',
        'date_of_birth',
        'nationality_id',
        'nationality_name',
        'nic',
        'passport',
        'tin',
        'sl_unique_digital_id_number',
        'country_code_personal_mobile',
        'personal_mobile_number',
        'country_code_fixed_mobile',
        'fixed_mobile_number',
        'personal_email',
        'permanent_country_id',
        'permanent_country_name',
        'permanent_block_house_number',
        'permanent_apartment_house_name',
        'permanent_street_name',
        'permanent_province_id',
        'permanent_district_id',
        'permanent_district_name',
        'permanent_city_id',
        'permanent_city_name',
        'permanent_postal_code',
        'permanent_residential_address',
        'is_same_as_permanent_address',
        'current_country_id',
        'current_country_name',
        'current_block_house_number',
        'current_apartment_house_name',
        'current_street_name',
        'current_province_id',
        'current_district_id',
        'current_district_name',
        'current_city_id',
        'current_city_name',
        'current_postal_code',
        'current_residential_address',
        'do_hold_employment_details',
        'designation_class_id',
        'designation_class_name',
        'designation_id',
        'other_designation',
        'institution_id',
        'other_institution',
        'country_code_office_mobile',
        'office_mobile_no',
        'office_address',
        'do_hold_other_country_residency',
        'created_by',
        'is_delete'
    ];
}
